ALTER TABLE "Refund" DROP CONSTRAINT IF EXISTS "Refund_orderId_key";
DROP INDEX IF EXISTS "Refund_orderId_key";
CREATE INDEX IF NOT EXISTS "Refund_orderId_status_createdAt_idx" ON "Refund"("orderId", "status", "createdAt");
ALTER TABLE "CollaborationRefundAllocation" ADD COLUMN IF NOT EXISTS "sellerPayoutReversal" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "CollaborationRefundAllocation" ADD COLUMN IF NOT EXISTS "platformFeeReversal" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "CollaborationAllocation" ADD COLUMN IF NOT EXISTS "remainingNetAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
UPDATE "CollaborationAllocation" SET "remainingNetAmount" = "netAmount" WHERE "remainingNetAmount" = 0;
ALTER TABLE "Delivery" ADD COLUMN IF NOT EXISTS "collaborationShipmentId" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "Delivery_collaborationShipmentId_key" ON "Delivery"("collaborationShipmentId");
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_collaborationShipmentId_fkey" FOREIGN KEY ("collaborationShipmentId") REFERENCES "CollaborationShipment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
