ALTER TABLE "Booking" ALTER COLUMN "customerId" DROP NOT NULL;
ALTER TABLE "Booking" ALTER COLUMN "providerId" DROP NOT NULL;
ALTER TABLE "Order" ALTER COLUMN "shopId" DROP NOT NULL;
ALTER TABLE "Order" ALTER COLUMN "sellerId" DROP NOT NULL;

CREATE TABLE IF NOT EXISTS "Refund" (
	"id" TEXT NOT NULL,
	"orderId" TEXT NOT NULL,
	"sellerId" TEXT,
	"customerId" TEXT,
	"amount" DECIMAL(12,2) NOT NULL,
	"currency" TEXT NOT NULL DEFAULT 'GHS',
	"reason" TEXT,
	"status" TEXT NOT NULL DEFAULT 'PENDING',
	"adminNotes" TEXT,
	"processedBy" TEXT,
	"processedAt" TIMESTAMP(3),
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "Refund_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "Refund_orderId_key" ON "Refund"("orderId");
CREATE INDEX IF NOT EXISTS "Refund_orderId_idx" ON "Refund"("orderId");
CREATE INDEX IF NOT EXISTS "Refund_sellerId_idx" ON "Refund"("sellerId");
CREATE INDEX IF NOT EXISTS "Refund_status_idx" ON "Refund"("status");
ALTER TABLE "Refund" DROP CONSTRAINT IF EXISTS "Refund_orderId_fkey";
ALTER TABLE "Refund" DROP CONSTRAINT IF EXISTS "Refund_customerId_fkey";
ALTER TABLE "Refund" DROP CONSTRAINT IF EXISTS "Refund_sellerId_fkey";
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Refund" ALTER COLUMN "sellerId" DROP NOT NULL;
ALTER TABLE "Dispute" ALTER COLUMN "customerId" DROP NOT NULL;
ALTER TABLE "Dispute" ALTER COLUMN "sellerId" DROP NOT NULL;
ALTER TABLE "Payout" ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE "Payout" ALTER COLUMN "payoutMethodId" DROP NOT NULL;
ALTER TABLE "SellerEarnings" ALTER COLUMN "sellerId" DROP NOT NULL;
ALTER TABLE "RiderEarnings" ALTER COLUMN "riderId" DROP NOT NULL;
ALTER TABLE "EmailCampaign" ALTER COLUMN "sentBy" DROP NOT NULL;
ALTER TABLE "PromoCode" ALTER COLUMN "createdBy" DROP NOT NULL;
ALTER TABLE "PublicNotice" ALTER COLUMN "createdBy" DROP NOT NULL;

ALTER TABLE "Booking" DROP CONSTRAINT IF EXISTS "Booking_customerId_fkey";
ALTER TABLE "Booking" DROP CONSTRAINT IF EXISTS "Booking_providerId_fkey";
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_customerId_fkey";
ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_sellerId_fkey";
ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_riderId_fkey";
ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_shopId_fkey";
ALTER TABLE "Order" ADD CONSTRAINT "Order_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_riderId_fkey" FOREIGN KEY ("riderId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Refund" DROP CONSTRAINT IF EXISTS "Refund_sellerId_fkey";
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Dispute" DROP CONSTRAINT IF EXISTS "Dispute_customerId_fkey";
ALTER TABLE "Dispute" DROP CONSTRAINT IF EXISTS "Dispute_sellerId_fkey";
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Payout" DROP CONSTRAINT IF EXISTS "Payout_userId_fkey";
ALTER TABLE "Payout" DROP CONSTRAINT IF EXISTS "Payout_payoutMethodId_fkey";
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_payoutMethodId_fkey" FOREIGN KEY ("payoutMethodId") REFERENCES "PayoutMethod"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "SellerEarnings" DROP CONSTRAINT IF EXISTS "SellerEarnings_sellerId_fkey";
ALTER TABLE "SellerEarnings" ADD CONSTRAINT "SellerEarnings_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RiderEarnings" DROP CONSTRAINT IF EXISTS "RiderEarnings_riderId_fkey";
ALTER TABLE "RiderEarnings" ADD CONSTRAINT "RiderEarnings_riderId_fkey" FOREIGN KEY ("riderId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EmailCampaign" DROP CONSTRAINT IF EXISTS "EmailCampaign_sentBy_fkey";
ALTER TABLE "EmailCampaign" ADD CONSTRAINT "EmailCampaign_sentBy_fkey" FOREIGN KEY ("sentBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PromoCode" DROP CONSTRAINT IF EXISTS "PromoCode_createdBy_fkey";
ALTER TABLE "PromoCode" ADD CONSTRAINT "PromoCode_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PublicNotice" DROP CONSTRAINT IF EXISTS "PublicNotice_createdBy_fkey";
ALTER TABLE "PublicNotice" ADD CONSTRAINT "PublicNotice_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
