'use client'

import React, { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { SellerSidebar } from '@/components/SellerSidebar'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { api } from '@/lib/api'

export default function EditProductPage() {
  const params = useParams(); const router = useRouter()
  const [product, setProduct] = useState<any>(null); const [categories, setCategories] = useState<any[]>([]); const [platformCategories, setPlatformCategories] = useState<any[]>([]); const [form, setForm] = useState<any>({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { const load = async () => { const response = await api.get<any>(`/seller/products/${params.id}`); if (!response.success) { setError(response.error || 'Product not found'); return }; const value = response.data; setProduct(value); setForm({ name: value.name, description: value.description, price: value.price, originalPrice: value.originalPrice || '', stock: value.stock, categoryId: value.categoryId, shopCategoryId: value.shopCategoryId || '', location: value.location, area: value.area || '', campus: value.campus || '', condition: value.condition, images: value.images?.map((image: any) => image.url).join('\n') || '' }); const [platformResponse, shop] = await Promise.all([api.get<any>('/categories'), api.get<any>('/seller/shop')]); setPlatformCategories(Array.isArray(platformResponse.data) ? platformResponse.data : []); if (shop.data?.shop) { const categoryResponse = await api.get<any>(`/shop-categories/shops/${shop.data.shop.id}`); setCategories(categoryResponse.data || []) } }; load() }, [params.id])
  const update = (field: string, value: any) => setForm((current: any) => ({ ...current, [field]: value }))
  const uploadImage = () => { const input = document.createElement('input'); input.type = 'file'; input.accept = 'image/jpeg,image/png,image/webp,image/gif'; input.onchange = async () => { const file = input.files?.[0]; if (!file) return; const body = new FormData(); body.append('image', file); const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || '/api'}/upload/image`, { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('token') || ''}` }, body }); const data = await response.json(); if (data.success) update('images', `${form.images ? `${form.images}\n` : ''}${data.data.url}`); else setError(data.error || 'Image upload failed') }; input.click() }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const response = await api.patch(`/products/${params.id}`, { ...form, price: Number(form.price), originalPrice: form.originalPrice ? Number(form.originalPrice) : undefined, stock: Number(form.stock), images: form.images.split('\n').map((url: string) => url.trim()).filter(Boolean) }); if (response.success) router.push('/seller/products'); else setError(response.error || 'Could not save product'); setSaving(false) }
  if (!product) return <SellerSidebar><Card className="p-8">{error || 'Loading product...'}</Card></SellerSidebar>
  return <SellerSidebar><div className="max-w-2xl space-y-6"><div><h1 className="font-display text-3xl font-bold text-warm-900">Edit Product</h1><p className="text-warm-800/60 mt-1">Update catalog information only.</p></div>{error && <div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}<Card className="p-5"><form onSubmit={submit} className="space-y-4"><Input label="Product name" value={form.name} onChange={e => update('name', e.target.value)} required /><label className="block text-sm font-medium">Description<textarea value={form.description} onChange={e => update('description', e.target.value)} className="mt-2 w-full rounded-xl border border-warm-200 p-3" rows={4} required /></label><div className="grid grid-cols-2 gap-3"><Input label="Price" type="number" min="0.01" step="0.01" value={form.price} onChange={e => update('price', e.target.value)} required /><Input label="Stock" type="number" min="0" value={form.stock} onChange={e => update('stock', e.target.value)} required /></div><Input label="Sale/original price" type="number" min="0" step="0.01" value={form.originalPrice} onChange={e => update('originalPrice', e.target.value)} /><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Platform category<select value={form.categoryId} onChange={e => update('categoryId', e.target.value)} className="mt-2 w-full rounded-xl border border-warm-200 p-3" required><option value="">Select category</option>{platformCategories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-sm font-medium">Shop category<select value={form.shopCategoryId} onChange={e => update('shopCategoryId', e.target.value)} className="mt-2 w-full rounded-xl border border-warm-200 p-3"><option value="">None</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div><label className="block text-sm font-medium">Image URLs, one per line<textarea value={form.images} onChange={e => update('images', e.target.value)} className="mt-2 w-full rounded-xl border border-warm-200 p-3" rows={3} /></label><Button type="button" variant="outline" onClick={uploadImage}>Upload product image</Button><div className="flex gap-3"><Button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save Product'}</Button><Button type="button" variant="ghost" onClick={() => router.back()}>Cancel</Button></div></form></Card></div></SellerSidebar>
}