ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "instructions" TEXT;
